server:
  port: 8672

spring:
  application:
    name: seller-client
  # mysql 属性配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.31.117:3306/custom_price_comparison
    username: root
    password: root
  mybaits:
    mapperLocations: classpath*:/mapper/*.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/